/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'activity-pages': ActivityPage;
    'tool-pages': ToolPage;
    posts: Post;
    categories: Category;
    tags: Tag;
    authors: Author;
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'activity-pages': ActivityPagesSelect<false> | ActivityPagesSelect<true>;
    'tool-pages': ToolPagesSelect<false> | ToolPagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    home: Home;
    'partners-page': PartnersPage;
    'about-page': AboutPage;
    'pet-parents-landing-page': PetParentsLandingPage;
    'professionals-landing-page': ProfessionalsLandingPage;
    'privacy-policy-page': PrivacyPolicyPage;
    'terms-and-conditions-page': TermsAndConditionsPage;
    'general-sales-conditions-page': GeneralSalesConditionsPage;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'partners-page': PartnersPageSelect<false> | PartnersPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'pet-parents-landing-page': PetParentsLandingPageSelect<false> | PetParentsLandingPageSelect<true>;
    'professionals-landing-page': ProfessionalsLandingPageSelect<false> | ProfessionalsLandingPageSelect<true>;
    'privacy-policy-page': PrivacyPolicyPageSelect<false> | PrivacyPolicyPageSelect<true>;
    'terms-and-conditions-page': TermsAndConditionsPageSelect<false> | TermsAndConditionsPageSelect<true>;
    'general-sales-conditions-page': GeneralSalesConditionsPageSelect<false> | GeneralSalesConditionsPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-pages".
 */
export interface ActivityPage {
  id: number;
  title: string;
  /**
   * Select an activity for this section
   */
  activityId?: string | null;
  /**
   * Rich text description of this activity page
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Add one or more sections to this activity page
   */
  sections: (
    | {
        title: string;
        layout: 'textLeft' | 'textRight' | 'textCenter';
        /**
         * Rich text content for this section
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Image to display alongside the text
         */
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textWithImage';
      }
    | {
        title: string;
        /**
         * Add questions and answers for this FAQ section
         */
        faqs: {
          question: string;
          /**
           * Provide a detailed answer to the question
           */
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        title: string;
        subtitle?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Select an activity for this section
         */
        activityId: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'professionals';
      }
  )[];
  /**
   * Auto-generated from the page title
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * When this page was/will be published
   */
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-pages".
 */
export interface ToolPage {
  id: number;
  /**
   * The main title of this tool page
   */
  title: string;
  /**
   * Add one or more sections to this tool page (text, FAQ, quiz, etc.)
   */
  sections: (
    | {
        /**
         * Hero section title
         */
        title: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Hero section description
         */
        description: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        layout: 'left' | 'center' | 'right';
        /**
         * Optional background image for the hero section
         */
        backgroundImage?: (number | null) | Media;
        /**
         * Optional background color for the hero section
         */
        backgroundColor?: ('primary' | 'secondary') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        title: string;
        layout: 'textLeft' | 'textRight' | 'textCenter';
        /**
         * Rich text content for this section
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Image to display alongside the text
         */
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textWithImage';
      }
    | {
        title: string;
        /**
         * Add questions and answers for this FAQ section
         */
        faqs: {
          question: string;
          /**
           * Provide a detailed answer to the question
           */
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        title?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Welcome message shown before quiz starts
         */
        introduction?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * How long the quiz typically takes to complete
         */
        estimatedCompletionTimeMinutes?: number | null;
        /**
         * List IDs in Brevo where contacts will be added when they unlock the report
         */
        brevoListIds?:
          | {
              listId: number;
              id?: string | null;
            }[]
          | null;
        /**
         * Define score ranges and their associated feedback. For normalized mode, use 0-100 scale. Ranges should not overlap.
         */
        scoreBands: {
          minScore: number;
          maxScore: number;
          label: string;
          /**
           * Detailed, supportive feedback for this score range (shown on website with custom components)
           */
          message: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          /**
           * Simple text message for email (no custom components, basic formatting only)
           */
          emailMessage: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          color?: ('success' | 'warning' | 'danger' | 'info' | 'neutral') | null;
          id?: string | null;
        }[];
        /**
         * Define sections and their questions. For flat quizzes, use a single section (e.g., 'General'). Each section has its own questions and optional recommendations.
         */
        sections: {
          name: string;
          /**
           * Optional description shown before questions in this section
           */
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          /**
           * Add all questions for this section. Questions will be displayed in order.
           */
          questions: {
            label: string;
            /**
             * Additional context or clarification (optional)
             */
            helperText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Add 2 or more answer choices for this question
             */
            choices: {
              label: string;
              /**
               * Points awarded for selecting this choice
               */
              points: number;
              /**
               * Optional explanation shown in detailed results
               */
              explanation?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            id?: string | null;
          }[];
          /**
           * Optional: Specific feedback for different score ranges within this section
           */
          scoreBands?:
            | {
                minScore: number;
                maxScore: number;
                label: string;
                /**
                 * Detailed, supportive feedback for this score range (shown on website with custom components)
                 */
                message: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                /**
                 * Simple text message for email (no custom components, basic formatting only)
                 */
                emailMessage: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                color?: ('success' | 'warning' | 'danger' | 'info' | 'neutral') | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'quiz';
      }
  )[];
  /**
   * Auto-generated from the page title (URL: /outils/{slug})
   */
  slug: string;
  /**
   * Draft pages are only visible in preview mode
   */
  status: 'draft' | 'published';
  /**
   * When this page was/will be published
   */
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Brief summary of the post (optional)
   */
  excerpt?: string | null;
  /**
   * Main image for the post
   */
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * URL-friendly version of the title (auto-generated)
   */
  slug: string;
  category: number | Category;
  tags?: (number | Tag)[] | null;
  author: number | Author;
  status: 'draft' | 'published';
  /**
   * When this post was/will be published
   */
  publishedAt?: string | null;
  /**
   * Estimated reading time in minutes (auto-calculated)
   */
  readingTime?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly version of the name (e.g., 'conseils', 'news')
   */
  slug: string;
  /**
   * Brief description of the category
   */
  description?: string | null;
  /**
   * Hex color for category display (e.g., #3B82F6)
   */
  color?: string | null;
  /**
   * Category image for display
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * URL-friendly version of the name
   */
  slug: string;
  /**
   * Optional description of the tag
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL-friendly version of the name
   */
  slug: string;
  /**
   * Author's email address
   */
  email?: string | null;
  /**
   * Author biography
   */
  bio?: string | null;
  /**
   * Author profile picture
   */
  avatar?: (number | null) | Media;
  socialLinks?: {
    twitter?: string | null;
    linkedin?: string | null;
    website?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'activity-pages';
        value: number | ActivityPage;
      } | null)
    | ({
        relationTo: 'tool-pages';
        value: number | ToolPage;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-pages_select".
 */
export interface ActivityPagesSelect<T extends boolean = true> {
  title?: T;
  activityId?: T;
  description?: T;
  sections?:
    | T
    | {
        textWithImage?:
          | T
          | {
              title?: T;
              layout?: T;
              content?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        professionals?:
          | T
          | {
              title?: T;
              subtitle?: T;
              activityId?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  status?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-pages_select".
 */
export interface ToolPagesSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              description?: T;
              layout?: T;
              backgroundImage?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        textWithImage?:
          | T
          | {
              title?: T;
              layout?: T;
              content?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quiz?:
          | T
          | {
              title?: T;
              introduction?: T;
              estimatedCompletionTimeMinutes?: T;
              brevoListIds?:
                | T
                | {
                    listId?: T;
                    id?: T;
                  };
              scoreBands?:
                | T
                | {
                    minScore?: T;
                    maxScore?: T;
                    label?: T;
                    message?: T;
                    emailMessage?: T;
                    color?: T;
                    id?: T;
                  };
              sections?:
                | T
                | {
                    name?: T;
                    description?: T;
                    questions?:
                      | T
                      | {
                          label?: T;
                          helperText?: T;
                          choices?:
                            | T
                            | {
                                label?: T;
                                points?: T;
                                explanation?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    scoreBands?:
                      | T
                      | {
                          minScore?: T;
                          maxScore?: T;
                          label?: T;
                          message?: T;
                          emailMessage?: T;
                          color?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  status?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  slug?: T;
  category?: T;
  tags?: T;
  author?: T;
  status?: T;
  publishedAt?: T;
  readingTime?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  email?: T;
  bio?: T;
  avatar?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        website?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Add questions and answers for the home page FAQ section
   */
  faqs?:
    | {
        question: string;
        /**
         * Provide a detailed answer to the question
         */
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-page".
 */
export interface PartnersPage {
  id: number;
  pageTitle: string;
  pageDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Add partners to display on the partners page
   */
  partners?:
    | {
        name: string;
        /**
         * Upload the partner's logo
         */
        logo: number | Media;
        description: string;
        url: string;
        promotionalCode?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    title: string;
    ctaButtonText: string;
    /**
     * Upload the hero background image
     */
    heroImage?: (number | null) | Media;
  };
  whyTobalgo: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    instagramEmbedUrl?: string | null;
  };
  legalRecognition: {
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  baltoSpark: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (number | null) | Media;
  };
  mission: {
    introText: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    missions: {
      missionNumber: number;
      missionText: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      };
      id?: string | null;
    }[];
    closingText: string;
    ctaText: string;
  };
  team: {
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    finalDescription: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ctaButtonText: string;
  };
  commitments: {
    title: string;
    sectionTitle: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    missionStatement: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (number | null) | Media;
    finalText: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  ministry: {
    title: string;
    paragraph1: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    paragraph2: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (number | null) | Media;
  };
  petition: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ctaButtonText: string;
    petitionUrl: string;
  };
  finalCta: {
    title: string;
    primaryButtonText: string;
    secondaryButtonText: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pet-parents-landing-page".
 */
export interface PetParentsLandingPage {
  id: number;
  hero: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ctaButtonText: string;
    /**
     * Upload the hero background image
     */
    heroImage?: (number | null) | Media;
  };
  introduction: {
    title: string;
    /**
     * Introduction text
     */
    longDescription: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  howItWorks: {
    title: string;
    steps?:
      | {
          stepNumber: number;
          stepTitle: string;
          stepDescription: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          stepImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  healthRecord: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ctaButtonText: string;
    sectionImage?: (number | null) | Media;
  };
  whyTobalgo: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    features?:
      | {
          featureTitle: string;
          /**
           * Short description displayed below the title
           */
          featureDescription: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  testimonials: {
    title: string;
    testimonialsList?:
      | {
          quote: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          author: string;
          authorImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    ctaButtonText: string;
  };
  faqs: {
    title: string;
    faqList?:
      | {
          question: string;
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
    ctaButtonText: string;
  };
  finalCta: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ctaButtonText: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professionals-landing-page".
 */
export interface ProfessionalsLandingPage {
  id: number;
  hero: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    ctaButtonText: string;
    /**
     * Upload the hero background image
     */
    heroImage?: (number | null) | Media;
  };
  benefits: {
    title: string;
    features?:
      | {
          featureTitle: string;
          featureDescription: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          featureImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pricing: {
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  faqs: {
    title: string;
    faqList?:
      | {
          question: string;
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
    ctaButtonText: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page".
 */
export interface PrivacyPolicyPage {
  id: number;
  pageTitle: string;
  pageContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions-page".
 */
export interface TermsAndConditionsPage {
  id: number;
  pageTitle: string;
  pageContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-sales-conditions-page".
 */
export interface GeneralSalesConditionsPage {
  id: number;
  pageTitle: string;
  pageContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-page_select".
 */
export interface PartnersPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageDescription?: T;
  partners?:
    | T
    | {
        name?: T;
        logo?: T;
        description?: T;
        url?: T;
        promotionalCode?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        ctaButtonText?: T;
        heroImage?: T;
      };
  whyTobalgo?:
    | T
    | {
        title?: T;
        description?: T;
        instagramEmbedUrl?: T;
      };
  legalRecognition?:
    | T
    | {
        description?: T;
      };
  baltoSpark?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  mission?:
    | T
    | {
        introText?: T;
        missions?:
          | T
          | {
              missionNumber?: T;
              missionText?: T;
              id?: T;
            };
        closingText?: T;
        ctaText?: T;
      };
  team?:
    | T
    | {
        title?: T;
        description?: T;
        finalDescription?: T;
        ctaButtonText?: T;
      };
  commitments?:
    | T
    | {
        title?: T;
        sectionTitle?: T;
        description?: T;
        missionStatement?: T;
        image?: T;
        finalText?: T;
      };
  ministry?:
    | T
    | {
        title?: T;
        paragraph1?: T;
        paragraph2?: T;
        image?: T;
      };
  petition?:
    | T
    | {
        title?: T;
        description?: T;
        ctaButtonText?: T;
        petitionUrl?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        primaryButtonText?: T;
        secondaryButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pet-parents-landing-page_select".
 */
export interface PetParentsLandingPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        ctaButtonText?: T;
        heroImage?: T;
      };
  introduction?:
    | T
    | {
        title?: T;
        longDescription?: T;
      };
  howItWorks?:
    | T
    | {
        title?: T;
        steps?:
          | T
          | {
              stepNumber?: T;
              stepTitle?: T;
              stepDescription?: T;
              stepImage?: T;
              id?: T;
            };
      };
  healthRecord?:
    | T
    | {
        title?: T;
        description?: T;
        ctaButtonText?: T;
        sectionImage?: T;
      };
  whyTobalgo?:
    | T
    | {
        title?: T;
        description?: T;
        features?:
          | T
          | {
              featureTitle?: T;
              featureDescription?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        title?: T;
        testimonialsList?:
          | T
          | {
              quote?: T;
              author?: T;
              authorImage?: T;
              id?: T;
            };
        ctaButtonText?: T;
      };
  faqs?:
    | T
    | {
        title?: T;
        faqList?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        ctaButtonText?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        description?: T;
        ctaButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professionals-landing-page_select".
 */
export interface ProfessionalsLandingPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        ctaButtonText?: T;
        heroImage?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        features?:
          | T
          | {
              featureTitle?: T;
              featureDescription?: T;
              featureImage?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        title?: T;
        description?: T;
      };
  faqs?:
    | T
    | {
        title?: T;
        faqList?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        ctaButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page_select".
 */
export interface PrivacyPolicyPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions-page_select".
 */
export interface TermsAndConditionsPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-sales-conditions-page_select".
 */
export interface GeneralSalesConditionsPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeBlock".
 */
export interface YouTubeBlock {
  /**
   * Enter a YouTube video URL (e.g., https://youtube.com/watch?v=dQw4w9WgXcQ)
   */
  videoURL: string;
  /**
   * Optional title to display above the video
   */
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtubeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  /**
   * The text displayed on the button
   */
  text: string;
  /**
   * The URL or relative path the button links to
   */
  link: string;
  /**
   * The alignment position of the button
   */
  position: 'left' | 'center' | 'right';
  /**
   * The size of the button
   */
  size: 'small' | 'default' | 'large';
  /**
   * The visual style variant of the button
   */
  variant: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextButton';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  /**
   * Define the header row with multiple cells. You can only have one header row.
   */
  header?:
    | {
        /**
         * Add or remove cells in the header row
         */
        cells?:
          | {
              /**
               * Enter header cell content
               */
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Define the table rows. Add or remove rows as needed.
   */
  rows: {
    /**
     * Add or remove cells in this row
     */
    cells?:
      | {
          /**
           * Enter cell content
           */
          content: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tableBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProfessionalsCarouselBlock".
 */
export interface ProfessionalsCarouselBlock {
  /**
   * Enter the activity ID to display professionals from that activity
   */
  activityId: string;
  /**
   * Choose between compact or extended card layouts
   */
  mode: 'compact' | 'extended';
  id?: string | null;
  blockName?: string | null;
  blockType: 'professionalsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}